### ISSUE TITLE
bug: missing files and types when installing

### ISSUE THREAD

**Issue by sawa-ko** [revoltchat/api#19]
When the package is installed there is only one index.js file left in the dist folder with no type files and no other files in the dist folder.

> As currently seen:

![image](https://user-images.githubusercontent.com/56084970/161356144-7f819a57-af6e-4d17-9074-67ef89cc53a9.png)

> As it should look:

![image](https://user-images.githubusercontent.com/56084970/161356220-8bfa4f93-2f82-478d-be24-741d8c44bf75.png)

**Comment by insertish** [comment]
Fixed this at some point.
