### ISSUE TITLE
bug: other users banners dont show up

### ISSUE THREAD

**Issue by siqnole** [revoltchat/api#22]
### What happened?

> *https://api.revolt.chat/users/{target} doesnt return the users background banner, only your own (the token used to make the api request).*

**Solution (but still bad):**

> make ANOTHER request to https://api.revolt.chat/users/{target}/profile and get the background there.

**pls use the method used in the https://api.revolt.chat/users/{target}/profile route and integrate it into https://api.revolt.chat/users/{target} if possible. :trollface: **

**Comment by insertish** [comment]
Profile data is kept separate to reduce bandwidth for sending user data.

**Comment by siqnole** [comment]
2 quick questions then:

- why is background a json object for fetch user profile if I can only get my own? (because it would make more sense if it was only on /users/@me)
- why when I fetch myself I can get my banner, but with anyone else it doesn't work?

**Comment by insertish** [comment]
I would consider including profile data on own user, but the get profile route always returns banners if they exist(?)

![image](https://user-images.githubusercontent.com/38285861/171705120-eda4a215-237c-4a18-ae9e-eec20bf37fe4.png)

**Comment by siqnole** [comment]
it always just gives me nothing when i try, which is quite odd but idk
