### ISSUE TITLE
Create isBot property in User interface

### ISSUE THREAD

**Issue by tiagoryandev** [revoltchat/api#4]
It would be a great idea to create one more property in the User interface, where it returns a Boolean value to check if the user is a bot.

```ts
export interface User {
    isBot: Boolean;
}
```

So it would be simpler to identify the user type directly by the `revolt.js` bookstore.

My Revolt Profile: `TiaGoiNsaNy`

**Comment by insertish** [comment]
The User objects typically come straight from the database and this change would ideally require duplicating the User struct to add `isBot` and then it'd also need a conversion, I feel like it'd get pretty mess quickly.

Does `typeof user.bot === 'object'` or `typeof user.bot !== 'undefined` not suffice? Currently extra bot information is attached for transparency sake and I'd rather not simplify it.

**Comment by elementh** [comment]
I'm with @insertish in this one; I think the current bot object is good enough, for example in the dotnet SDK I'm preparing I just default it to false if not present and that's about it!
